import logging
from typing import Any, Dict, Optional, Tuple

import torch
import torch.nn as nn
from sbi import inference as inference
from sbi.inference.posteriors.mcmc_posterior import MCMCPosterior
from sbi.inference.potentials import likelihood_estimator_based_potential
from torch import Tensor

from sbibm.algorithms.sbi.utils import (
    wrap_posterior,
    wrap_prior_dist,
    wrap_simulator_fn,
)
from sbibm.tasks.task import Task


class SynthLikNet(nn.Module):
    """
    bootstrap a per-sample likelihood from input prior values `theta` under
    the assumption that all `x_i = sim(theta_i)` were generated by a multivariate
    normal along `x_i.shape[-1]`.

    Class to be used with SBI's SNLE algorithms. We used SynthLikNet as a quick
    implementation of the classical synthetic likelihood algorithm published by
    Wood (2010). It is reported as SL on the website and in the paper's appendix.

    Wood, S. N. (2010). "Statistical inference for noisy nonlinear ecological
    dynamic systems". Nature 466 (August), 1102–1104.
    """

    def __init__(self, simulator, num_simulations_per_step=100, diag_eps=0.0):
        super(SynthLikNet, self).__init__()
        self.simulator = simulator
        self.num_simulations_per_step = num_simulations_per_step
        self.diag_eps = diag_eps

        # dummy parameter to make LikelihoodBasedPosterior happy
        # (deduces device from SynthLikNet.parameters())
        self.estimated_mn = torch.nn.parameter.UninitializedParameter(
            requires_grad=False
        )

    def forward(self, *args, **kwargs):
        raise NotImplementedError

    def log_prob(
        self,
        inputs: Tensor,
        condition: Optional[Tensor] = None,
        **kwargs: Any,
    ) -> Tensor:
        if condition is None:
            raise ValueError("`condition` must be provided.")

        thetas = condition  # (batch_dim, dim_theta)
        x = inputs

        if thetas.ndim == 1:
            thetas = thetas.unsqueeze(0)

        # sbi convention:
        # inputs: (sample_dim, batch_dim, event_dim) or (batch_dim, event_dim)
        if x.ndim == 2:
            x = x.unsqueeze(0)  # -> (1, batch_dim, event_dim)
        elif x.ndim != 3:
            raise ValueError(
                f"`inputs` must have ndim 2 or 3, got {x.ndim} with shape {x.shape}."
            )

        sample_dim, batch_dim, dim_x = x.shape

        if thetas.shape[0] != batch_dim:
            raise ValueError(
                f"Mismatched batch sizes: inputs has batch {batch_dim}, "
                f"condition has batch {thetas.shape[0]}."
            )

        log_probs = []
        for i in range(batch_dim):
            theta_i = thetas[i].reshape(1, -1)

            xs = self.simulator(theta_i.repeat(self.num_simulations_per_step, 1))
            if xs.ndim == 1:
                xs = xs.unsqueeze(-1)
            elif xs.ndim > 2:
                xs = xs.reshape(xs.shape[0], -1)

            m = xs.mean(dim=0)
            xm = xs - m
            S = xm.T @ xm / (xs.shape[0] - 1)
            S = S + self.diag_eps * torch.eye(
                xs.shape[1], device=xs.device, dtype=xs.dtype
            )

            if dim_x != m.shape[-1]:
                raise ValueError(
                    f"Observation event dim {dim_x} does not match synthetic "
                    f"likelihood dim {m.shape[-1]} for batch {i}."
                )

            dist = torch.distributions.MultivariateNormal(
                loc=m,
                covariance_matrix=S,
                validate_args=False,
            )

            # x[:, i, :] has shape (sample_dim, dim_x)
            log_prob_i = dist.log_prob(x[:, i, :])  # shape: (sample_dim,)
            log_probs.append(log_prob_i)

        # stack over batch dimension -> (sample_dim, batch_dim)
        return torch.stack(log_probs, dim=1)

    def sample(self, *args, **kwargs):
        raise NotImplementedError

    def train(self, *args, **kwargs):
        pass

    def eval(self, *args, **kwargs):
        pass


def run(
    task: Task,
    num_samples: int,
    num_simulations: int,
    num_simulations_per_step: int = 100,
    num_observation: Optional[int] = None,
    observation: Optional[torch.Tensor] = None,
    automatic_transforms_enabled: bool = False,
    mcmc_method: str = "slice_np",
    mcmc_parameters: Dict[str, Any] = {},
    diag_eps: float = 0.0,
) -> Tuple[torch.Tensor, int, Optional[torch.Tensor]]:
    """Runs (S)NLE from `sbi`

    Args:
        task: Task instance
        num_observation: Observation number to load, alternative to `observation`
        observation: Observation, alternative to `num_observation`
        num_samples: Number of samples to generate from posterior
        num_simulations: Simulation budget
        num_simulations_per_step: Number of simulations per MCMC step
        automatic_transforms_enabled: Whether to enable automatic transforms
        mcmc_method: MCMC method
        mcmc_parameters: MCMC parameters
        diag_eps: Epsilon applied to diagonal

    Returns:
        Samples from posterior, number of simulator calls, log probability of true params if computable
    """
    assert not (num_observation is None and observation is None)
    assert not (num_observation is not None and observation is not None)

    log = logging.getLogger(__name__)

    log.info(f"Running SL")

    prior = task.get_prior_dist()
    if observation is None:
        observation = task.get_observation(num_observation)

    simulator = task.get_simulator()

    transforms = task._get_transforms(automatic_transforms_enabled)["parameters"]
    if automatic_transforms_enabled:
        prior = wrap_prior_dist(prior, transforms)
        simulator = wrap_simulator_fn(simulator, transforms)

    likelihood_estimator = SynthLikNet(
        simulator=simulator,
        num_simulations_per_step=num_simulations_per_step,
        diag_eps=diag_eps,
    )

    potential_fn, theta_transform = likelihood_estimator_based_potential(
        likelihood_estimator=likelihood_estimator,
        prior=prior,
        x_o=None,
        enable_transform=not automatic_transforms_enabled,
    )
    posterior = MCMCPosterior(
        potential_fn=potential_fn,
        proposal=prior,
        theta_transform=theta_transform,
        method=mcmc_method,
        x_shape=observation.shape,
        **mcmc_parameters,
    )

    posterior.set_default_x(observation)

    posterior = wrap_posterior(posterior, transforms)

    # assert simulator.num_simulations == num_simulations

    samples = posterior.sample((num_samples,)).detach()

    return samples, simulator.num_simulations, None
